spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: bands-api
  datasource:
    url: jdbc:h2:mem:bandsapi
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

spotify:
  clientId: 3e47dde041644fc3a49f07ddce7c1732
  clientSecret: 47ae8346fb814b9a87a57fd0b145ca5b
  redirectUri: http://localhost:8080
