spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: bands-api
  datasource:
    url: jdbc:h2:file:./database/h2;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

spotify:
  client:
    id: 3e47dde041644fc3a49f07ddce7c1732
    secret: 47ae8346fb814b9a87a57fd0b145ca5b
    redirectUri: http://localhost:8080

jwt:
  secret: 358aaa4d470f681859d0486d56234fc1e1e9fa9b3fb74fbb2e4d5e765e51f0ecbadae71c87676cc16f41115dda7c82924b2c2ffe2c48997d4d5173b20e1a561a